# Generated by Django 2.2.28 on 2025-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
